/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalygroundRouteImport } from './routes/palyground'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardAtmeRouteImport } from './routes/dashboard/[@]me'
import { Route as DashboardGroupIdRouteImport } from './routes/dashboard/$groupId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardAtmeIndexRouteImport } from './routes/dashboard/[@]me/index'
import { Route as DashboardAtmePrivateRouteImport } from './routes/dashboard/[@]me/$Private'
import { Route as DashboardGroupIdChatIdRouteImport } from './routes/dashboard/$groupId/$chatId'

const PalygroundRoute = PalygroundRouteImport.update({
  id: '/palyground',
  path: '/palyground',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAtmeRoute = DashboardAtmeRouteImport.update({
  id: '/@me',
  path: '/@me',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupIdRoute = DashboardGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardAtmeIndexRoute = DashboardAtmeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAtmeRoute,
} as any)
const DashboardAtmePrivateRoute = DashboardAtmePrivateRouteImport.update({
  id: '/$Private',
  path: '/$Private',
  getParentRoute: () => DashboardAtmeRoute,
} as any)
const DashboardGroupIdChatIdRoute = DashboardGroupIdChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => DashboardGroupIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/palyground': typeof PalygroundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$groupId': typeof DashboardGroupIdRouteWithChildren
  '/dashboard/@me': typeof DashboardAtmeRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/$groupId/$chatId': typeof DashboardGroupIdChatIdRoute
  '/dashboard/@me/$Private': typeof DashboardAtmePrivateRoute
  '/dashboard/@me/': typeof DashboardAtmeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/palyground': typeof PalygroundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$groupId': typeof DashboardGroupIdRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/$groupId/$chatId': typeof DashboardGroupIdChatIdRoute
  '/dashboard/@me/$Private': typeof DashboardAtmePrivateRoute
  '/dashboard/@me': typeof DashboardAtmeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/palyground': typeof PalygroundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$groupId': typeof DashboardGroupIdRouteWithChildren
  '/dashboard/@me': typeof DashboardAtmeRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/$groupId/$chatId': typeof DashboardGroupIdChatIdRoute
  '/dashboard/@me/$Private': typeof DashboardAtmePrivateRoute
  '/dashboard/@me/': typeof DashboardAtmeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/palyground'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/$groupId'
    | '/dashboard/@me'
    | '/dashboard/profile'
    | '/auth/'
    | '/dashboard/$groupId/$chatId'
    | '/dashboard/@me/$Private'
    | '/dashboard/@me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/palyground'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/$groupId'
    | '/dashboard/profile'
    | '/auth'
    | '/dashboard/$groupId/$chatId'
    | '/dashboard/@me/$Private'
    | '/dashboard/@me'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/palyground'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/$groupId'
    | '/dashboard/@me'
    | '/dashboard/profile'
    | '/auth/'
    | '/dashboard/$groupId/$chatId'
    | '/dashboard/@me/$Private'
    | '/dashboard/@me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PalygroundRoute: typeof PalygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palyground': {
      id: '/palyground'
      path: '/palyground'
      fullPath: '/palyground'
      preLoaderRoute: typeof PalygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/@me': {
      id: '/dashboard/@me'
      path: '/@me'
      fullPath: '/dashboard/@me'
      preLoaderRoute: typeof DashboardAtmeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$groupId': {
      id: '/dashboard/$groupId'
      path: '/$groupId'
      fullPath: '/dashboard/$groupId'
      preLoaderRoute: typeof DashboardGroupIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/@me/': {
      id: '/dashboard/@me/'
      path: '/'
      fullPath: '/dashboard/@me/'
      preLoaderRoute: typeof DashboardAtmeIndexRouteImport
      parentRoute: typeof DashboardAtmeRoute
    }
    '/dashboard/@me/$Private': {
      id: '/dashboard/@me/$Private'
      path: '/$Private'
      fullPath: '/dashboard/@me/$Private'
      preLoaderRoute: typeof DashboardAtmePrivateRouteImport
      parentRoute: typeof DashboardAtmeRoute
    }
    '/dashboard/$groupId/$chatId': {
      id: '/dashboard/$groupId/$chatId'
      path: '/$chatId'
      fullPath: '/dashboard/$groupId/$chatId'
      preLoaderRoute: typeof DashboardGroupIdChatIdRouteImport
      parentRoute: typeof DashboardGroupIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardGroupIdRouteChildren {
  DashboardGroupIdChatIdRoute: typeof DashboardGroupIdChatIdRoute
}

const DashboardGroupIdRouteChildren: DashboardGroupIdRouteChildren = {
  DashboardGroupIdChatIdRoute: DashboardGroupIdChatIdRoute,
}

const DashboardGroupIdRouteWithChildren =
  DashboardGroupIdRoute._addFileChildren(DashboardGroupIdRouteChildren)

interface DashboardAtmeRouteChildren {
  DashboardAtmePrivateRoute: typeof DashboardAtmePrivateRoute
  DashboardAtmeIndexRoute: typeof DashboardAtmeIndexRoute
}

const DashboardAtmeRouteChildren: DashboardAtmeRouteChildren = {
  DashboardAtmePrivateRoute: DashboardAtmePrivateRoute,
  DashboardAtmeIndexRoute: DashboardAtmeIndexRoute,
}

const DashboardAtmeRouteWithChildren = DashboardAtmeRoute._addFileChildren(
  DashboardAtmeRouteChildren,
)

interface DashboardRouteChildren {
  DashboardGroupIdRoute: typeof DashboardGroupIdRouteWithChildren
  DashboardAtmeRoute: typeof DashboardAtmeRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGroupIdRoute: DashboardGroupIdRouteWithChildren,
  DashboardAtmeRoute: DashboardAtmeRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PalygroundRoute: PalygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
